apiVersion: v1
kind: ConfigMap
metadata:
    namespace: gitops
    name: nginx-app-vol
data:
    index.html: <h1>hello world Romani2</h1>
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-app
  namespace: gitops
  annotations:
    environment: prod
    organization: sales
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - { name: data, mountPath: /usr/share/nginx/html }
      volumes:
        - name: data
          configMap:
            name: nginx-app-vol